// GENERATED by tools/gen_resources.py from tools/entity_specs.py.
// Do not hand-edit: edit the spec and re-run. tools/check_all.sh fails if
// this file and the spec disagree, because a box that moves here without
// its texture net moving too is a silent skin corruption, not an error.
package com.cadykaya.interregnum.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public final class ShrineKeeperGeometry {
    private ShrineKeeperGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_robe_lower = root.addOrReplaceChild(
                "robe_lower",
                CubeListBuilder.create()
                .texOffs(0, 30)
                .addBox(-4.5F, 0.0F, -3.5F, 9.0F, 10.0F, 7.0F),
                PartPose.offset(0.0F, 14.0F, 0.0F));
        PartDefinition p_torso = root.addOrReplaceChild(
                "torso",
                CubeListBuilder.create()
                .texOffs(32, 14)
                .addBox(-4.0F, -11.0F, -3.0F, 8.0F, 11.0F, 6.0F),
                PartPose.offset(0.0F, 14.0F, 0.0F));
        PartDefinition p_head = root.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                .texOffs(0, 14)
                .addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F)
                .texOffs(0, 0)
                .addBox(-4.5F, -9.0F, -4.5F, 9.0F, 5.0F, 9.0F),
                PartPose.offset(0.0F, 3.0F, 0.0F));
        PartDefinition p_right_arm = root.addOrReplaceChild(
                "right_arm",
                CubeListBuilder.create()
                .texOffs(32, 31)
                .addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F),
                PartPose.offset(-5.5F, 4.0F, 0.0F));
        PartDefinition p_left_arm = root.addOrReplaceChild(
                "left_arm",
                CubeListBuilder.create()
                .mirror()
                .texOffs(32, 31)
                .addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F)
                .mirror(false),
                PartPose.offset(5.5F, 4.0F, 0.0F));
        PartDefinition p_ledger = p_left_arm.addOrReplaceChild(
                "ledger",
                CubeListBuilder.create()
                .texOffs(0, 47)
                .addBox(-3.5F, 4.0F, -4.5F, 7.0F, 5.0F, 7.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
