package com.cadykaya.interregnum.worldgen;

import net.minecraft.core.HolderGetter;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;
import net.minecraft.world.level.levelgen.placement.BiomeFilter;
import net.minecraft.world.level.levelgen.placement.InSquarePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.levelgen.placement.PlacementModifier;
import net.minecraft.world.level.levelgen.placement.RarityFilter;
import net.minecraft.world.level.levelgen.heightproviders.UniformHeight;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.VerticalAnchor;

import net.minecraft.core.HolderSet;
import net.minecraft.tags.BiomeTags;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.neoforged.neoforge.common.world.BiomeModifier;
import net.neoforged.neoforge.common.world.BiomeModifiers;
import net.neoforged.neoforge.registries.NeoForgeRegistries;

import java.util.List;

import com.cadykaya.interregnum.Interregnum;
import com.cadykaya.interregnum.registry.ModFeatures;

/**
 * Worldgen definitions, as data, generated by `gradle runServerData`.
 *
 * Worldgen JSON is deep, repetitive and fails silently when mistyped -- exactly the
 * profile of a thing that should be code (docs/WORLDGEN.md). Defining it here means
 * a wrong registry key is a compile error rather than a shrine that never appears.
 */
public final class ModWorldgen {
    private ModWorldgen() {}

    public static ResourceKey<ConfiguredFeature<?, ?>> configured(String name) {
        return ResourceKey.create(Registries.CONFIGURED_FEATURE,
                Identifier.fromNamespaceAndPath(Interregnum.MOD_ID, name));
    }

    public static ResourceKey<PlacedFeature> placed(String name) {
        return ResourceKey.create(Registries.PLACED_FEATURE,
                Identifier.fromNamespaceAndPath(Interregnum.MOD_ID, name));
    }

    public static final ResourceKey<ConfiguredFeature<?, ?>> SHRINE_CONFIGURED = configured("shrine");
    public static final ResourceKey<PlacedFeature> SHRINE_PLACED = placed("shrine");

    public static final ResourceKey<BiomeModifier> ADD_SHRINES =
            ResourceKey.create(NeoForgeRegistries.Keys.BIOME_MODIFIERS,
                    Identifier.fromNamespaceAndPath(Interregnum.MOD_ID, "add_shrines"));

    public static void bootstrapConfigured(BootstrapContext<ConfiguredFeature<?, ?>> ctx) {
        ctx.register(SHRINE_CONFIGURED, new ConfiguredFeature<>(
                ModFeatures.SHRINE.get(), NoneFeatureConfiguration.INSTANCE));
    }

    public static void bootstrapPlaced(BootstrapContext<PlacedFeature> ctx) {
        HolderGetter<ConfiguredFeature<?, ?>> features = ctx.lookup(Registries.CONFIGURED_FEATURE);

        // Rarity first, then position: the cheapest, most-eliminating modifier goes
        // first so the rest never runs on a chunk that was never a candidate
        // (docs/WORLDGEN.md). RarityFilter(N) means "one chunk in N tries".
        //
        // MEASURED, not guessed. tools/shrine_rate_probe.sh attempts a placement at
        // every chunk centre in a grid of real terrain and counts the answers:
        // **46% of natural sites are level enough** for MAX_RELIEF=2 (which also
        // says that check is selective rather than crippling). Real density is
        // therefore rarity / 0.46.
        //
        // Target: a shrine roughly every 120 chunks -- about six minutes of walking
        // -- because these are Chapter 0 FURNITURE. A player has to pass enough of
        // them that they stop looking, so that the one with a heart in it reads as
        // "another shrine" right up until it does not. 120 x 0.46 = 55.
        //
        // Re-run the probe after any change to MAX_RELIEF: that check and this
        // number multiply, and moving one silently moves the density.
        // Still [NEEDS PLAYTEST]: only a person can say whether six minutes feels
        // like furniture or like litter.
        ctx.register(SHRINE_PLACED, new PlacedFeature(
                features.getOrThrow(SHRINE_CONFIGURED),
                List.<PlacementModifier>of(
                        RarityFilter.onAverageOnceEvery(55),
                        InSquarePlacement.spread(),
                        HeightRangePlacement.of(UniformHeight.of(
                                VerticalAnchor.absolute(-64), VerticalAnchor.absolute(320))),
                        BiomeFilter.biome())));
    }

    /**
     * Put shrines into the world without editing anyone's biome.
     *
     * Targets the OVERWORLD **tag**, never a list of biome ids: a modifier naming
     * twelve biomes misses the thirteenth, misses every modded biome, and breaks
     * the day Mojang adds one (docs/WORLDGEN.md).
     *
     * SURFACE_STRUCTURES, not VEGETAL_DECORATION: the shrine paves ground and must
     * run before grass and trees are scattered over it, or it generates underneath
     * a forest floor.
     */
    public static void bootstrapBiomeModifiers(BootstrapContext<BiomeModifier> ctx) {
        HolderGetter<Biome> biomes = ctx.lookup(Registries.BIOME);
        HolderGetter<PlacedFeature> placed = ctx.lookup(Registries.PLACED_FEATURE);
        ctx.register(ADD_SHRINES, new BiomeModifiers.AddFeaturesBiomeModifier(
                biomes.getOrThrow(BiomeTags.IS_OVERWORLD),
                HolderSet.direct(placed.getOrThrow(SHRINE_PLACED)),
                GenerationStep.Decoration.SURFACE_STRUCTURES));
    }
}
