"""Generate model/blockstate/pack JSON for interregnum. Deterministic, like all art.

Only formats stable for years are generated here (blockstates, block models,
pack.mcmeta shell). Item MODEL definitions are deliberately NOT generated: the
item-model system churned during the 1.21 line and its 26.x shape is unverified
(docs/MODELS.md). They get written when the real toolchain can confirm the format.
"""
import json, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(REPO, "src/main/resources/assets/interregnum")

CUBE_ALL_BLOCKS = ["shrine_stone", "shrine_stone_carved"]

# name -> (side_texture, end_texture). Pillar-shaped blocks; the blockstate carries
# the axis, which is why these get variants rather than a single model.
COLUMN_BLOCKS = {"warning_stele": ("stele_side", "stele_top")}

def w(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(obj, fh, indent=2)
        fh.write("\n")
    print("wrote", os.path.relpath(path, REPO))

for name in CUBE_ALL_BLOCKS:
    w(os.path.join(ASSETS, "models/block", name + ".json"),
      {"parent": "minecraft:block/cube_all",
       "textures": {"all": f"interregnum:block/{name}"}})
    w(os.path.join(ASSETS, "blockstates", name + ".json"),
      {"variants": {"": {"model": f"interregnum:block/{name}"}}})

# The Warden statue: 4 facings x 2 states. Two models (asleep / awake) differing
# only in the front texture, and the blockstate rotates them.
_STATUE_ROT = {"north": 0, "east": 90, "south": 180, "west": 270}
for suffix, front in (("", "warden_statue_front"), ("_woken", "warden_statue_front_woken")):
    w(os.path.join(ASSETS, "models/block", "warden_statue" + suffix + ".json"),
      {"parent": "minecraft:block/orientable",
       "textures": {
           "front": f"interregnum:block/{front}",
           "side": "interregnum:block/warden_statue_side",
           "top": "interregnum:block/warden_statue_top",
       }})
_statue_variants = {}
for facing, rot in _STATUE_ROT.items():
    for woken in (False, True):
        model = "interregnum:block/warden_statue" + ("_woken" if woken else "")
        entry = {"model": model}
        if rot:
            entry["y"] = rot
        _statue_variants[f"facing={facing},woken={str(woken).lower()}"] = entry
w(os.path.join(ASSETS, "blockstates", "warden_statue.json"), {"variants": _statue_variants})

for name, (side, end) in COLUMN_BLOCKS.items():
    tex = {"side": f"interregnum:block/{side}", "end": f"interregnum:block/{end}"}
    w(os.path.join(ASSETS, "models/block", name + ".json"),
      {"parent": "minecraft:block/cube_column", "textures": tex})
    w(os.path.join(ASSETS, "models/block", name + "_horizontal.json"),
      {"parent": "minecraft:block/cube_column_horizontal", "textures": tex})
    w(os.path.join(ASSETS, "blockstates", name + ".json"),
      {"variants": {
          "axis=y": {"model": f"interregnum:block/{name}"},
          "axis=z": {"model": f"interregnum:block/{name}_horizontal", "x": 90},
          "axis=x": {"model": f"interregnum:block/{name}_horizontal", "x": 90, "y": 90},
      }})


# --- entity geometry, as Java ------------------------------------------------
#
# A mob's layer definition is Java, not a resource, so it cannot simply be a data
# file the game reads -- but it is still DATA, needed identically by the texture
# painter, the model, and tools/entity_view.py. Generating it from the one spec in
# tools/entity_specs.py is what stops those three drifting: a box resized in Java
# alone would garble the skin silently, because nothing in Minecraft checks that a
# net fits the box sampling it.
#
# Only the geometry is generated. Animation is design, and lives hand-written in
# WardenModel.java next door, which calls into this.
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from entity_specs import SPECS                        # noqa: E402

JAVA = os.path.join(REPO, "src/main/java/com/cadykaya/interregnum/client")


def _num(v):
    """Java float literal. Whole numbers keep a .0 so the source reads uniformly."""
    return f"{float(v):.1f}F" if float(v) == int(v) else f"{float(v)}F"


def entity_geometry(name, spec):
    cls = "".join(p.capitalize() for p in name.split("_")) + "Geometry"
    L = [
        "// GENERATED by tools/gen_resources.py from tools/entity_specs.py.",
        "// Do not hand-edit: edit the spec and re-run. tools/check_all.sh fails if",
        "// this file and the spec disagree, because a box that moves here without",
        "// its texture net moving too is a silent skin corruption, not an error.",
        "package com.cadykaya.interregnum.client;",
        "",
        "import net.minecraft.client.model.geom.PartPose;",
        "import net.minecraft.client.model.geom.builders.CubeListBuilder;",
        "import net.minecraft.client.model.geom.builders.LayerDefinition;",
        "import net.minecraft.client.model.geom.builders.MeshDefinition;",
        "import net.minecraft.client.model.geom.builders.PartDefinition;",
        "",
        f"public final class {cls} {{",
        f"    private {cls}() {{}}",
        "",
        "    public static LayerDefinition createBodyLayer() {",
        "        MeshDefinition mesh = new MeshDefinition();",
        "        PartDefinition root = mesh.getRoot();",
    ]
    declared = {}
    for part in spec.parts:
        parent = "root" if part.parent is None else declared[part.parent]
        var = "p_" + part.name
        declared[part.name] = var
        cubes = ["CubeListBuilder.create()"]
        for b in part.boxes:
            if b.mirror:
                cubes.append("                .mirror()")
            cubes.append(f"                .texOffs({b.uv[0]}, {b.uv[1]})")
            cubes.append("                .addBox("
                         + ", ".join(_num(v) for v in b.origin) + ", "
                         + ", ".join(_num(v) for v in b.size) + ")")
            if b.mirror:
                cubes.append("                .mirror(false)")
        L.append(f"        PartDefinition {var} = {parent}.addOrReplaceChild(")
        L.append(f'                "{part.name}",')
        L.append("                " + "\n".join(cubes) + ",")
        L.append("                PartPose.offset("
                 + ", ".join(_num(v) for v in part.pivot) + "));")
    L += [
        f"        return LayerDefinition.create(mesh, {spec.sheet[0]}, {spec.sheet[1]});",
        "    }",
        "}",
        "",
    ]
    os.makedirs(JAVA, exist_ok=True)
    path = os.path.join(JAVA, cls + ".java")
    with open(path, "w") as fh:
        fh.write("\n".join(L))
    print("wrote", os.path.relpath(path, REPO))


for _name, _spec in SPECS.items():
    entity_geometry(_name, _spec)
